name: amigo_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  chopper: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  form_field_validator: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.8.4+2
  json_annotation: ^4.1.0
  nfc_manager: ^3.1.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  chopper_generator: ^4.0.2
  json_serializable: ^5.0.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/figma/

  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf
        - asset: fonts/DMSerifDisplay-Italic.ttf
          style: italic
    - family: Karla
      fonts:
        - asset: fonts/Karla-VariableFont_wght.ttf
        - asset: fonts/Karla-Italic-VariableFont_wght.ttf
          style: italic
