name: amigoapp
description: AmigoApp

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+000100

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  chopper: ^4.0.4
  collection: ^1.15.0
  equatable: ^2.0.3
  firebase_analytics: ^9.1.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  form_field_validator: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  jitsi_meet: ^4.0.0
  json_annotation: ^4.4.0
  nfc_manager: ^3.1.1
  provider: ^6.0.2
  url_launcher: ^6.0.20
  logger: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.4
  mockito: ^5.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/figma/

  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf
        - asset: fonts/DMSerifDisplay-Italic.ttf
          style: italic
    - family: Karla
      fonts:
        - asset: fonts/Karla-VariableFont_wght.ttf
        - asset: fonts/Karla-Italic-VariableFont_wght.ttf
          style: italic
