// Mocks generated by Mockito 5.1.0 from annotations
// in amigoapp/test/provider/call_provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:amigoapp/src/dto/call_token_dto.dart' as _i10;
import 'package:amigoapp/src/dto/group_dto.dart' as _i2;
import 'package:amigoapp/src/dto/person_dto.dart' as _i7;
import 'package:amigoapp/src/provider/group_provider.dart' as _i5;
import 'package:amigoapp/src/service/api/call_api_service.dart' as _i9;
import 'package:amigoapp/src/service/navigation_service.dart' as _i11;
import 'package:amigoapp/src/service/tracking.dart' as _i12;
import 'package:chopper/chopper.dart' as _i3;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGroupDto_0 extends _i1.Fake implements _i2.GroupDto {}

class _FakeChopperClient_1 extends _i1.Fake implements _i3.ChopperClient {}

class _FakeType_2 extends _i1.Fake implements Type {}

class _FakeResponse_3<BodyType> extends _i1.Fake
    implements _i3.Response<BodyType> {}

class _FakeGlobalKey_4<T extends _i4.State<_i4.StatefulWidget>> extends _i1.Fake
    implements _i4.GlobalKey<T> {}

/// A class which mocks [GroupProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupProvider extends _i1.Mock implements _i5.GroupProvider {
  MockGroupProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void refreshSelectedGroup() =>
      super.noSuchMethod(Invocation.method(#refreshSelectedGroup, []),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i2.GroupDto> getSelectedGroup() =>
      (super.noSuchMethod(Invocation.method(#getSelectedGroup, []),
              returnValue: Future<_i2.GroupDto>.value(_FakeGroupDto_0()))
          as _i6.Future<_i2.GroupDto>);
  @override
  void selectGroupMember(_i7.PersonDto? personDto) =>
      super.noSuchMethod(Invocation.method(#selectGroupMember, [personDto]),
          returnValueForMissingStub: null);
  @override
  void addListener(_i8.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i8.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [CallApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallApiService extends _i1.Mock implements _i9.CallApiService {
  MockCallApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChopperClient get client =>
      (super.noSuchMethod(Invocation.getter(#client),
          returnValue: _FakeChopperClient_1()) as _i3.ChopperClient);
  @override
  set client(_i3.ChopperClient? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  Type get definitionType =>
      (super.noSuchMethod(Invocation.getter(#definitionType),
          returnValue: _FakeType_2()) as Type);
  @override
  _i6.Future<_i3.Response<_i10.CallTokenDto>> createCall(
          String? receiverId, String? callType, {String? personId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createCall, [receiverId, callType], {#personId: personId}),
              returnValue: Future<_i3.Response<_i10.CallTokenDto>>.value(
                  _FakeResponse_3<_i10.CallTokenDto>()))
          as _i6.Future<_i3.Response<_i10.CallTokenDto>>);
  @override
  _i6.Future<_i3.Response<_i10.CallTokenDto>> getCall(String? id) =>
      (super.noSuchMethod(Invocation.method(#getCall, [id]),
              returnValue: Future<_i3.Response<_i10.CallTokenDto>>.value(
                  _FakeResponse_3<_i10.CallTokenDto>()))
          as _i6.Future<_i3.Response<_i10.CallTokenDto>>);
  @override
  _i6.Future<_i3.Response<List<_i10.CallTokenDto>>> getSentCalls() =>
      (super.noSuchMethod(Invocation.method(#getSentCalls, []),
              returnValue: Future<_i3.Response<List<_i10.CallTokenDto>>>.value(
                  _FakeResponse_3<List<_i10.CallTokenDto>>()))
          as _i6.Future<_i3.Response<List<_i10.CallTokenDto>>>);
  @override
  _i6.Future<_i3.Response<List<_i10.CallTokenDto>>> getReceivedCalls() =>
      (super.noSuchMethod(Invocation.method(#getReceivedCalls, []),
              returnValue: Future<_i3.Response<List<_i10.CallTokenDto>>>.value(
                  _FakeResponse_3<List<_i10.CallTokenDto>>()))
          as _i6.Future<_i3.Response<List<_i10.CallTokenDto>>>);
  @override
  _i6.Future<_i3.Response<_i10.CallTokenDto>> acceptCall(String? id) =>
      (super.noSuchMethod(Invocation.method(#acceptCall, [id]),
              returnValue: Future<_i3.Response<_i10.CallTokenDto>>.value(
                  _FakeResponse_3<_i10.CallTokenDto>()))
          as _i6.Future<_i3.Response<_i10.CallTokenDto>>);
  @override
  _i6.Future<_i3.Response<_i10.CallTokenDto>> cancelCall(String? id) =>
      (super.noSuchMethod(Invocation.method(#cancelCall, [id]),
              returnValue: Future<_i3.Response<_i10.CallTokenDto>>.value(
                  _FakeResponse_3<_i10.CallTokenDto>()))
          as _i6.Future<_i3.Response<_i10.CallTokenDto>>);
  @override
  _i6.Future<_i3.Response<_i10.CallTokenDto>> denyCall(String? id) =>
      (super.noSuchMethod(Invocation.method(#denyCall, [id]),
              returnValue: Future<_i3.Response<_i10.CallTokenDto>>.value(
                  _FakeResponse_3<_i10.CallTokenDto>()))
          as _i6.Future<_i3.Response<_i10.CallTokenDto>>);
  @override
  _i6.Future<_i3.Response<_i10.CallTokenDto>> finishCall(String? id) =>
      (super.noSuchMethod(Invocation.method(#finishCall, [id]),
              returnValue: Future<_i3.Response<_i10.CallTokenDto>>.value(
                  _FakeResponse_3<_i10.CallTokenDto>()))
          as _i6.Future<_i3.Response<_i10.CallTokenDto>>);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i11.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GlobalKey<_i4.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(Invocation.getter(#navigatorKey),
              returnValue: _FakeGlobalKey_4<_i4.NavigatorState>())
          as _i4.GlobalKey<_i4.NavigatorState>);
  @override
  _i6.Future<dynamic> navigateTo(String? routeName,
          {bool? removeAllRoutes = false, Object? arguments}) =>
      (super.noSuchMethod(
          Invocation.method(#navigateTo, [routeName],
              {#removeAllRoutes: removeAllRoutes, #arguments: arguments}),
          returnValue: Future<dynamic>.value()) as _i6.Future<dynamic>);
  @override
  void navigateBack() =>
      super.noSuchMethod(Invocation.method(#navigateBack, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [Tracking].
///
/// See the documentation for Mockito's code generation for more information.
class MockTracking extends _i1.Mock implements _i12.Tracking {
  MockTracking() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init({bool? analyticsStorageConsentGranted = true}) =>
      (super.noSuchMethod(
          Invocation.method(#init, [], {
            #analyticsStorageConsentGranted: analyticsStorageConsentGranted
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void logEvent(String? name) =>
      super.noSuchMethod(Invocation.method(#logEvent, [name]),
          returnValueForMissingStub: null);
  @override
  void logEventVariant(String? name, String? variant) =>
      super.noSuchMethod(Invocation.method(#logEventVariant, [name, variant]),
          returnValueForMissingStub: null);
  @override
  void setCurrentScreen(String? screenName) =>
      super.noSuchMethod(Invocation.method(#setCurrentScreen, [screenName]),
          returnValueForMissingStub: null);
  @override
  void logError(dynamic exception, String? reason, StackTrace? stackTrace) =>
      super.noSuchMethod(
          Invocation.method(#logError, [exception, reason, stackTrace]),
          returnValueForMissingStub: null);
}
